# The name of the github workflow
name: Hustle Template CI
# Trigger the workflow on following actions
on:
  # On pull requests for the following branches
  pull_request:
    branches:
      - template
      - super-template
  # On push commits for the
  push:
    branches:
      - template
# Run the following jobs in this workflow
jobs:
  # Run pre-commit checks
  # Ensure the code & commits are formatted correctly and upto spec
  lint-and-build:
    # job runs on a unbuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Install pre-commit dependencies
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install golang.org/x/lint/golint@latest
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - uses: pre-commit/action@v3.0.0
      - name: Build
        run:  go build ./...
  # Run unit tests in the project
  # and report the coverage to codacy
  test-and-coverage:
    # job runs on a unbuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Run Unit Tests
        run:  go test ./... -coverprofile=coverage.out
      - name: Report Coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          api-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.out
          force-coverage-parser: go
          language: go